GET http://localhost:8080/regbsser/providerregistry
Accept: application/json

###
GET http://localhost:8080/regbsser/providerregistry?page=2&pageSize=1
Accept: application/json

###
GET http://localhost:8080/regbsser/providerregistry/bosa:dp-citizen:ebox
Content-Type: application/json

###
GET http://localhost:8080/regbsser/providerregistry/bosa:dp-citizen:ebox/images/BOSA-M-NL/medium/content
Content-Type: application/octet-stream

###
GET http://localhost:8080/regbsser/providerregistry/sfpd:broker-citizen:ebox/images/SFPD-S-DE/small/content
Content-Type: application/octet-stream

###
GET http://localhost:8080/regbsser/providerregistry/vo:dp-citizen:ebox/images/MAGDA-L-FR/large/content
Content-Type: application/octet-stream


